title: Aud5
author: Manoj
email: aud5amp@gmail.com
description: >
  This is a demo website of Aud5 amplifiers, made available by Mikrotek Incorporated based at Palarivattom, Kochi.

plugins: 
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
#- posts.md
#- github.md

footer_icons:
- username: AUD5-amp
  url: https://aud5.github.io
  icon: icon-github.svg

paginate: 0

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
